name: agile_tech
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

scripts:
  gen: "fluttergen -c pubspec.yaml"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  graphql_flutter: ^5.1.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cloudinary_flutter: ^1.1.0
  cloudinary_url_gen: ^1.3.0
  http: ^0.13.6
  cloudinary_public: ^0.23.1
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-ThinItalic.ttf

flutter_gen:
  output: lib/utils/gen/
  fonts:
    enabled: true
    outputs:
      class_name: FontFamilyToken